export * as system from './system/storage'
export * as timestamp from './timestamp/storage'
export * as balances from './balances/storage'
export * as tokens from './tokens/storage'
export * as zenlinkProtocol from './zenlink-protocol/storage'
export * as farming from './farming/storage'
export * as assetRegistry from './asset-registry/storage'
export * as oracle from './oracle/storage'
